# Generated by Django 2.1.3 on 2018-11-23 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan_app', '0002_remove_userloaninfo_loan1'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaninfo',
            name='loanee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loanee', to=settings.AUTH_USER_MODEL),
        ),
    ]
